@startuml

class LoginController {
  authenticateLogin(email)
  checkCredentials(email, password)
  getUserByEmail(email)
  setUser(user)
}


class LoginUI {
}

class DataBase {
 checkEmail(email)
  checkCredentials(email, password)
  getUserByEmail(email)
}

class UserSession {
getInstance().setUser(user)
}


class LoginHandler {
  authenticateLogin(email, password)
  setuser(user)
  checkCredentials(email, password)
  getUserByEmail(email)
}

LoginUI ..> LoginController
LoginController ..> LoginHandler
LoginHandler ..> UserSession
LoginHandler ..> DataBase


@enduml