@startuml
skinparam classAttributeIconSize 0




class UpdateMedicineController {
  +getMedicinesList()
  +setStock(quantity)
}

class UpdateMedicineUI  {
}

class MedicineHandler{
    +listMedicines = getMedicinesList()
    +setStock(quantity)
}

class DataBase{
    +getMedicinesList()
    +updateStock(quantity)
}




UpdateMedicineUI  ..> UpdateMedicineController
UpdateMedicineController ..> MedicineHandler
MedicineHandler ..> DataBase