@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":UpdateMedicineUI" as UI
participant ":UpdateMedicineController" as CTRL
participant "MedicineHandler" as HANDLER
participant "Database" as DAT


activate ADM
ADM -> UI : The Administrator chooses to update the stock of a medicine in the system.
activate UI

UI -> CTRL : getMedicinesList()
activate CTRL

CTRL -> HANDLER : listMedicines = getMedicinesList()

activate HANDLER

HANDLER -> DAT ** : getMedicinesList()
deactivate CTRL
deactivate HANDLER

UI --> ADM : The system shows the list of medicines and asks the administrator to choose one to update

deactivate UI

ADM -> UI : The administrator enters the medicine to update.
activate UI


UI -> ADM : The System requests the quantity to add to stock.
deactivate UI

ADM -> UI : The Administrator enters the quantity

activate UI

UI -> CTRL : setStock(quantity)
activate CTRL

CTRL -> HANDLER : setStock(quantity)
activate HANDLER

HANDLER -> DAT : updateStock(quantity)
activate DAT

deactivate CTRL
deactivate HANDLER
deactivate DAT


UI -> ADM : update the stock and informs about the success of the operation.

deactivate UI
deactivate ADM