@startuml
skinparam classAttributeIconSize 0

class UpdateMedicineController {
  +updateMedicine(id)
}

class UpdateMedicineUI {
}

class MedicineHandler{
    +updateMedicine(id)
}

class Product {
  -String id
  -String name
  -String description
  -double price
  -double weight
  
}

class Administrator{
  -String email
  -String password 
}

class Pharmacy {
  -String id
  -String name
  -int quantityScooters
  }
  
class Stock {
  -String productID
  -int quantity
}


UpdateMedicineUI ..> UpdateMedicineController
UpdateMedicineController ..> MedicineHandler
UpdateMedicineController ..> Stock
MedicineHandler ..> Stock

Pharmacy "1" -- "1.." Product: Has >
Product "1" -- "1" Stock: Has > 
Administrator "1" -- "1.." Pharmacy: Manages >

@enduml