 @startuml
class NonRegisteredUser {
}

class Client {
  -String name
  -String email
  -String nif
  -String password
  -int credits
}

class Address {
  -double latitude
  -double longitude
  -String street
}

class CreditCard {
  -int number
  -int monthExpiration
  -int yearExpiration
  -int ccv
}



NonRegisteredUser "1" -- "1" Client: Becomes >
Client "1" -- "1" Address: Has >
Client "1" -- "1" CreditCard: Has >

@enduml
