@startuml
autonumber

actor "Non-Registered user" as ADM
participant ":RegistUserUI" as UI
participant ":RegistUserController" as CTRL
participant "User" as _ORG
participant "user: User" as ORG
participant "add: Address" as ADD
participant "ccd: CreditCard" as CDD
participant "EmailAPI" as API
participant ":UserHandler" as USH
participant ":DataBase" as DBE


activate ADM
ADM -> UI : begins the registration process of an user
activate UI

UI --> ADM : requests information about the user (e.g. name,email,NIF, password, credits, street,latitude,longitude, number, monthExpiration, yearExpiration, ccv)
deactivate UI

ADM -> UI : inserts the information
activate UI
UI -> CTRL : sendEmail(email)
activate CTRL


CTRL -> API: sendEmail(email)
activate API
deactivate API
deactivate CTRL
UI -> ADM : shows a message that an email was send to confirm
deactivate UI

ADM -> UI : confirms and begins the registration process of an user
activate UI
UI -> CTRL : newUser(name,email,NIF, password, credits, street,latitude,longitude, number, monthExpiration, yearExpiration, ccv)
activate CTRL




CTRL -> _ORG: address = newAddress(latitude, longitude, street)
activate _ORG
_ORG --> ADD ** : create(latitude, longitude, street)
deactivate _ORG

CTRL -> _ORG: creditCard = newCreditCard(number, monthExpiration, yearExpiration, ccv)
activate _ORG
_ORG --> CDD ** : create(number, monthExpiration, yearExpiration, ccv)
deactivate _ORG

CTRL --> ORG ** : create(name, email, nif, , password, credits, address, creditCard)


CTRL -> ORG: saveUser()
activate ORG
ORG -> USH: addUser(user)
activate USH
USH -> DBE: save(name, email, nif, password, credits, address, creditCard)
deactivate USH
deactivate ORG
activate DBE
deactivate DBE


deactivate CTRL
UI --> ADM : successful operation
deactivate UI

deactivate ADM
@enduml
