@startuml
autonumber

actor "Client" as COL
participant ":RemoveFromCartUI" as UI
participant ":RemoveFromCartController" as CTRL
participant ":UserSession" as SESS
participant ":CartHandler" as CART


activate COL

COL -> UI : Initializes the remove from cart operation
activate UI




UI -> CTRL :removeFromCart()
activate CTRL

CTRL -> SESS : getSessionID()


deactivate CTRL

UI --> COL : requests the product to be removed from the cart



deactivate UI


COL -> UI :selects the product that wants to remove
activate UI
UI --> COL : removes the product and informs the success of the operation
deactivate UI

deactivate COL

@enduml