@startuml
autonumber

actor "Client" as COL
participant ":RemoveFromCartUI" as UI
participant ":RemoveFromCartController" as CTRL
participant ":UserSession" as SESS
participant "cart\n:Cart" as CT
participant ":CartHandler" as CART

participant ":DataBase" as DB




activate COL

COL -> UI : Initializes the remove from cart operation
activate UI




UI -> CTRL :cart=showCart()
activate CTRL

CTRL -> SESS : user = getUserSession()
activate SESS
deactivate SESS

CTRL -> CART : cart=getCartByClientID(user.id)
activate CART

deactivate CT





CART -> DB : cart=getCart(id)
activate DB
deactivate DB
deactivate CART




deactivate CTRL

UI --> COL : requests the product to be removed from the cart



deactivate UI


COL -> UI :selects the product that wants to remove
activate UI

UI -> CTRL : removesProds(prodID)
activate CTRL
CTRL -> CT : removeFromCart(prodID)
activate CT
CT -> CART : removeFromCart(prodID,cartID)
deactivate CT
activate CART




CART -> DB : removeFromCart(prodID,cartID)
activate DB
deactivate DB
deactivate CART
deactivate CT
deactivate CTRL



UI --> COL : removes the product and informs the success of the operation
deactivate UI

deactivate COL

@enduml