@startuml
autonumber
actor "Courier" as COR

activate COR
COR -> ":System" : Requests the parking of the scooter
activate ":System"
":System" --> COR : checks whether the park has places available,\n authorize the parking and update the number of scooters parked
deactivate ":System"


deactivate COR
@enduml
