@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":AddMedicineUI" as UI
participant ":AddMedicineController" as CTRL
participant "med: Medicine" as MED
participant "MedicineHandler" as HANDLER
participant ":DataBase" as DB


activate ADM
ADM -> UI : The Administrator initiates the adding of a medicine to the system.
activate UI

UI --> ADM : The system asks for the data (id, name, description, price, weight ).

deactivate UI

ADM -> UI : The administrator writes the necessary data.
activate UI

UI -> ADM : The System shows the data and asks for confirmation.
deactivate UI

ADM -> UI : The Administrator confirms.
activate UI

UI -> CTRL : setNewMedicineData (id, name, description, price, weight)
activate CTRL

CTRL --> MED ** : create(id, name, description, price, weight)
CTRL --> MED : saveMedicine(med)
activate MED

MED --> HANDLER: addMedicine(med)
activate HANDLER

HANDLER -> DB : addMedicine(id, name, description, price, weight)
activate DB


UI -> ADM : registers the data and informs about the success of the operation.


deactivate UI
deactivate ADM