@startuml
autonumber
actor "Administrator" as Admin

activate Admin
Admin -> ":System" : initiates the adding of a medicine
":System" --> Admin : requests the necessary data \n(id, name, description, price, weight)
deactivate ":System"

Admin -> ":System" : enters the data
activate ":System"
":System" --> Admin :  presents the data and asks for confirmation
deactivate ":System"

Admin -> ":System" : confirms the data
activate ":System"
":System" --> Admin : informs that the medicine was added with success 
deactivate ":System"

@enduml