@startuml
skinparam classAttributeIconSize 0

class AddMedicineController {
  +setNewMedicineData (id, name, description, price, weight)
}

class AddMedicineUI {
}

class MedicineHandler{
    +addMedicine(med)
}

class DataBase{
   +addMedicine (id, name, description, price, weight)
}

class Product {
  -String id
  -String name
  -String description
  -double price
  -double weight
  
  +create(id, name, description, price, weight)
  +saveMedicine(med)
}

class Administrator{
  -String email
  -String password 
}

class Pharmacy {
  -String id
  -String name
  -int quantityScooters
  }

AddMedicineUI ..> AddMedicineController
AddMedicineController ..> Product
Product ..> MedicineHandler
MedicineHandler ..> DataBase

Pharmacy "1" -- "1.." Product: Has >
Administrator "1" -- "1.." Pharmacy: Manages >

@enduml