@startuml
autonumber
'hide footbox
actor "Client" as COL


participant ":CheckoutUI" as UI
participant ":CheckoutController" as CTRL
participant ":UserSession" as SESS
participant "cart\n:Cart" as CT
participant ":CartHandler" as CART
participant ":DataBase" as DB

activate COL

COL -> UI : begins the checkout process
activate UI

UI -> CTRL : cart=getCart()
activate CTRL



CTRL -> SESS : user = getUserSession()
activate SESS
deactivate SESS

CTRL -> CART : cart=getCartByClientID(user.id)
activate CART

deactivate CT

CART -> DB : cart=getCart(id)
activate DB
deactivate DB
deactivate CART
deactivate CTRL
UI --> COL: shows the cart and waits for confirmation
deactivate UI
COL -> UI : confirms
activate UI
deactivate UI



deactivate COL





@enduml
