@startuml
autonumber

actor "Client" as COL
activate COL

COL -> ":System" :begins the checkout process
activate ":System"

":System" --> COL : shows the cart and waits for confirmation
deactivate ":System"
COL -> ":System" : confirms
activate ":System"
":System" --> COL : shows information about current credit card and asks for confirmation
deactivate ":System"

COL -> ":System" :confirms
activate ":System"
":System" --> COL : operation success
deactivate ":System"


deactivate COL

@enduml