@startuml
autonumber
actor "Administrator" as Admin

activate Admin
Admin -> ":System" : chooses to remove a medicine
activate ":System"
":System" --> Admin : requestes the id of the medicine to be removed
deactivate ":System"
Admin -> ":System" : enters the id
activate ":System"
":System" --> Admin :  presents the medicine and asks for confirmation
deactivate ":System"

Admin -> ":System" : confirms
activate ":System"
":System" --> Admin : success removing the medicine 
deactivate ":System"

@enduml