@startuml
autonumber
'hide footbox
actor "Courier" as COL


participant ":CourierUI" as UI
participant ":PickUpOrderController" as CTRL
participant ":OrdersHandler" as ORD
participant ":Graph" as GRA
participant ":Physics" as PH
participant ":del:Delivery" as DELI
participant ":DeliverysHandler" as DEH
participant ":DataBase" as DB

activate COL

COL -> UI :iniciates the choosing order operation
activate UI

UI -> CTRL: ordersList = getUndoneOrders()
activate CTRL
CTRL -> ORD : ordersList = getUndoneOrders()
activate ORD
ORD -> DB: ordersList = getUndoneOrders()
activate DB
deactivate DB

deactivate ORD
deactivate CTRL

UI --> COL : shows list and asks to insert one order id


deactivate UI

COL -> UI :picks up the order giving id (Sent by email)
activate UI
UI -> CTRL :processOrder(id)
activate CTRL
CTRL -> ORD :order=getOrderByID(id)
activate ORD
ORD -> DB: order=getOrderByID(id)
activate DB
deactivate DB
deactivate ORD
CTRL -> GRA :pathList=shorthestPath(order)
activate GRA
deactivate GRA
CTRL -> GRA :distance=getDistance(pathList)
activate GRA
deactivate GRA
CTRL -> PH :necessaryEnergy=getNecessaryEnergy(pathList)
activate PH
deactivate PH
CTRL -> PH :weigth=getOrdersWeight(order)
activate PH
deactivate PH
CTRL -> DELI**: create(necessaryEnergy,distance,weight)

CTRL -> DELI : save()
activate DELI

DELI -> DEH : addDelivery(del)
deactivate DELI
activate DEH

deactivate DEH

DEH -> DB : save(id,necessaryEnergy,distance,weight)
activate DB
deactivate DB
deactivate DEH


deactivate CTRL





UI --> COL : Show best path and necessary energy

deactivate UI





@enduml
