@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":AddCourierUI" as UI
participant ":AddCourierController" as CTRL
participant "cour: Courier" as COUCOU
participant "CourierHandler" as HANDLER
participant ":DataBase" as DB


activate ADM
ADM -> UI : The Administrator initiates the adding of a courier to the system.
activate UI

UI --> ADM : The system asks for the data (name, email, NIF, social security number, maxWeightCapacity).

deactivate UI

ADM -> UI : The administrator writes the necessary data.
activate UI

UI -> ADM : The System shows the data and asks for confirmation.
deactivate UI

ADM -> UI : The Administrator confirms.
activate UI

UI -> CTRL : setNewCourierData (name, email, NIF, socialSecurityNumber, maxWeightCapacity)
activate CTRL

CTRL -> COUCOU ** :  create(name, email, NIF,socialSecurityNumber, maxWeightCapacity)
CTRL -> COUCOU  : saveCourier(cour)
activate COUCOU

COUCOU -> HANDLER : addCourier(cour)
activate HANDLER

HANDLER -> DB : addCourier (name, email, NIF, socialSecurityNumber, maxWeightCapacity)
activate DB



UI -> ADM : registers the data and informs about the success of the operation.


deactivate UI
deactivate ADM



@enduml